### ISSUE TITLE
Not thread safe

### ISSUE THREAD

**Issue by Sc00bz** [LoupVaillant/Monocypher#1]
You should remove "static" from "sv": https://github.com/LoupVaillant/Monocypher/blob/master/src/sha512.c#L4

**Comment by LoupVaillant** [comment]
Those static functions are not mutable state. (Nor are the numerous `static const` constant). How is is not thread safe?

**Comment by Sc00bz** [comment]
Oh wait I thought static functions didn't use the stack unless it's calling a function (ie all explicit and implicit variables are declared as static). Also I thought static class functions were different than static functions just in a different way. Ah never tried it but this is indeed invalid syntax ```static void Class::function() { ... }``` (since the whole not using the stack isn't a thing). I've literally held this misconception for the better part of a decade.

**Comment by LoupVaillant** [comment]
Okay, thanks for the clarification. Time to close the issue then :-)
