### ISSUE TITLE
Underscores not visible in the docs on Google Chrome for Windows 10

### ISSUE THREAD

**Issue by cursey** [LoupVaillant/Monocypher#103]
On Google Chrome (version `67.0.3396.99`) for Windows 10 the underscores present in the documentation do not show up.

![chrome_2018-07-05_19-16-55](https://user-images.githubusercontent.com/5798459/42356591-2c9d6204-8088-11e8-96fc-2af574e33f98.png)

**Comment by LoupVaillant** [comment]
Oh, that… it's one of the many things that broke with the ongoing site tweak/redesign. I'll fix it as soon as I can.

**Comment by cursey** [comment]
Sounds good. Keep up the good work 👍

**Comment by LoupVaillant** [comment]
[There](https://monocypher.org/manual/aead), should be fixed. Do reopen if I missed something important.
