### ISSUE TITLE
C++ compile Settings

### ISSUE THREAD

**Issue by skyformat99** [LoupVaillant/Monocypher#11]
thanks for your great work。
To make a small suggestion, add the following code to the head and tail of the h file:

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

**Comment by CuleX** [comment]
You should be able to build Monocypher as C *and* C++. Did you run into a configuration where this wasn't possible?

**Comment by LoupVaillant** [comment]
> You should be able to build Monocypher as C and C++.

Yep. This makes the proposed change out of scope. I'm closing the issue.

If however someone does have trouble compiling Monocypher as C++ (even if it's just a warning), I don't want to let them down. Don't hesitate to file a separate issue if that happens.
