### ISSUE TITLE
size_t to int converting warnings in line 1583 and 1595

### ISSUE THREAD

**Issue by mireiner** [LoupVaillant/Monocypher#111]
Hi there,

I found some minor flaws (I guess cosmetic ones): 
Compiling monocypher v2.0.5 Visual Studio 2017 v15.9.3 gives two warning messages:

Line 1583: warning C4267: "function": conversion from 'size_t' to 'int', possible loss of data

Line 1595: warning C4267: "Initialising": conversion from 'size_t' to 'int', possible loss of data

Monocypher v2.0.3 compiled without these warnings.

**Comment by LoupVaillant** [comment]
Cosmetic indeed.

The warning Line 1583 is incomprehensible. Here's the line:

    FOR (i,   0, 256) { adds[i] = scalar_bit(scalar, i); }

The `FOR` macro declares `size_t` index `i`, `adds[]` is an `uint8_t` array, and `scalar_bit()` returns an int already (only zero or one, by the way). I see no conversion from `size_t` to `int` here. There would be a possible loss of data indeed if `scalar_bit()` returned values other than 0 and 1, but then the compiler should complain about a conversion from `int` to `uint8_t`. I'm not sure it's worth fixing.

The other warning is equally wrong, but it's comprehensible. I'll change the type of `j`.

**Comment by mikejsavage** [comment]
`static int scalar_bit(const u8 s[32], int i)`, it's complaining about converting `i` in the function call

MSVC is very spammy at high warning settings so probably not worth spending too much time on it

**Comment by LoupVaillant** [comment]
Ah, I see, thanks. That said, `i` is an index, and indices in Monocypher are all `size_t` for nitpicking reasons (and consistency). I'll change it.

(Also, definitely no loss of data, since `i` cannot possibly exceed 255.)

**Comment by LoupVaillant** [comment]
By the way, even though MSVC is spammy, I like to fix warnings for usability reasons: without warning, users can just do whatever they set out to do, no fuss, no questions asked. With warnings, users will wonder whether this is a false positive. Best case, this is a loss of time. Worst case, this is a loss of _trust_. So I'm glad @mireiner reported it.

Now this is not worth making a new release, but I have something else in the works which is (I'm working on a [secure channel protocol](https://github.com/LoupVaillant/Monocypher-Handshake), and should soon integrate it in Monocypher).

**Comment by fscoto** [comment]
Late note, but I feel like it's important: The infamous [Debian OpenSSL RNG bug stemmed from quelling a warning generated by Valgrind](https://www.schneier.com/blog/archives/2008/05/random_number_b.html). Cleaning up spurious warnings will also mean that your package maintainers won't suddenly decide to rip out some critical part of the code.

**Comment by LoupVaillant** [comment]
Hmm, so that's more serious that I thought. Thank goodness this one was easy to clean up.
