### ISSUE TITLE
package for Void linux

### ISSUE THREAD

**Issue by cr6git** [LoupVaillant/Monocypher#16]
Hello ! 
I proposed a package for Void linux, see my Pull Request [#7407](https://github.com/voidlinux/void-packages/pull/7407). 

Regards.

**Comment by LoupVaillant** [comment]
Excellent, thank you!

Don't hesitate to submit a pull request to add Void linux to the list of known distribution in the README.md when this is accepted. (Or just respond here if you prefer.)

**Comment by cr6git** [comment]
I was too enthusiastic... 
But the truth is, I am not skilled enough to deal with crypto stuff, sorry.

**Comment by LoupVaillant** [comment]
Don't worry, the Monocypher repository is a bit of a mess, and currently doesn't facilitate packaging —this has little to do with crypto. I'm currently working on it, and should have a proper release (with a useful, *standard* makefile) by the end of the week. You should then be able to package it properly.

I'm re-opening the issue to keep track of the attempt. We'll close this once they've either accepted the patch, or we know Monocypher won't be accepted at all. Don't give up!

**Comment by cr6git** [comment]
@LoupVaillant : "Don't give up!" 

You're right. 
I wish to thank you for your encouragement and your support. 
I was in a very bad mood at the time, sorry... 

Now it's ok, I'll try again. :)

**Comment by LoupVaillant** [comment]
Just so you know, I'm preparing the next version. It's *almost* out. We only need some work in the manual, and a review of #38 (which unfortunately may trigger a minor incompatibility).

The build system however is all good. The makefile may now be used for the installation process. Making a package should now be easier. Just keep in mind that an update is coming, and you probably want your package to reflect that when it happens.

**Comment by cr6git** [comment]
In [#38](https://github.com/LoupVaillant/Monocypher/issues/38) you said: "Tested with GCC 5.4.0, -O3 optimisations." 

For information, in Void we use GCC 6.3.0, -O2 optimisations.

**Comment by LoupVaillant** [comment]
Then Void should be good (`-O2`, it looked reasonable with my compiler).

But that's no longer a problem since `crypto_memcmp` is now gone, replaced by fixed size `crypto_verify` functions, which generate much less code, and have zero conditional branch. Reasonable optimisation settings and hardening are good, but some users just won't ignore the performance `-O3` can give them (with Argon2i and Blake2b, the boost is significant).

Next release is imminent. The code should not change, I only need to review the manual.

**Comment by LoupVaillant** [comment]
Hi, I've released Monocypher 2.0.0 recently, still with the nice makefile to build and install, and man pages.  Feeling like having another go at making a Void package?

**Comment by cr6git** [comment]
Hi @LoupVaillant ! See [#12040](https://github.com/voidlinux/void-packages/pull/12040) :wink: 

Regards.

**Comment by LoupVaillant** [comment]
Nice, good work! We can close this now, thanks!

**Comment by cr6git** [comment]
`xbps-install -S monocypher`

**Comment by LoupVaillant** [comment]
[Noted!](https://monocypher.org/download/)
