### ISSUE TITLE
Javascript version

### ISSUE THREAD

**Issue by kingsleyh** [LoupVaillant/Monocypher#172]
Hi,

Are there any existing javascript ports of this library anywhere? I would like to know if it's possible to generate keypair / sign / verify in javascript in the browser.

Also I tried this library but it was unable to verify the signature.

https://github.com/indutny/elliptic

```javascript
var EdDSA = require('elliptic').eddsa;
var ec = new EdDSA('ed25519');
var message = "2baf1f40105d9501fe319a8ec463fdf4325a2a5df445adf3f572f626253678c9";
var pub_key = "432d30feab0a2edc07ff3907ef4f9d9649b8dd06f7738925230893ed77a129a0";
var key = ec.keyFromPublic(pub_key, 'hex');
var sig = 'f6133d58f4258cac4ee59041986efef64ccce672123c6846ff4a92d842e580ef9070692d84e1e5d1323d29fd4553f3cc7411e182099033bf8e85382b86168404';
key.verify(message, sig)
```

Maybe something to do with the hashibng

Thanks for a great library

**Comment by kingsleyh** [comment]
Any suggestions would be appreciated :)

**Comment by LoupVaillant** [comment]
Hi,

I am not aware of a JavaScript port of Monocypher. However, you can almost certainly use Emscripten to compile it to asm.js or web assembly. If that's not an option, I have heard good things about [TweetNaCL.js](https://tweetnacl.js.org/).

---

I guess you have generated the public key and signature with Monocypher? There's a catch: By default, Monocypher implements EdDSA with Blake2b and Edwards25519. The library you are testing almost certainly implements EdDSA with *SHA-512* and Edwards25519 (also known as Ed25519).

Monocypher has an option to use Ed25519, see the [manual](https://monocypher.org/manual/optional/ed25519) (requires the [optional files](https://github.com/LoupVaillant/Monocypher/tree/master/src/optional)).

**Comment by kingsleyh** [comment]
Thanks for the help. Does this mean that TweetNaCL.js will work with Monocypher straight away or I will still need to use the optional files and generate using Ed25519?

**Comment by fscoto** [comment]
No, you need the optional files and generate with Ed25519 to interoperate with essentially *anything* that isn't Monocypher, including TweetNaCl.js and the elliptic library in with the `'ed25519'` option.

For clarification: Ed25519 refers to EdDSA with SHA-512 as the hash function, Edwards25519 as the curve and a specific set of parameters based on the elliptic curve. Monocypher uses this for `crypto_sign()` *except* for the hash function being BLAKE2b, so its signatures are incompatible (I can go into detail if you want to know about the rationale behind this).

Since you need to work with another library, you'll need to compile Monocypher with support for Ed25519 and then use the `crypto_ed25519_sign_public_key()`, `crypto_ed25519_sign()` and `crypto_ed25519_check()` functions instead of their counterparts without `*_ed25519*` in the name.

**Comment by tankf33der** [comment]
@kingsleyh 
There is [demo](https://git.envs.net/mpech/emscripten-monocypher) repo for idea.

**Comment by kingsleyh** [comment]
Ok understood - thanks very much :)

**Comment by LoupVaillant** [comment]
You're welcome. Closing this for now, don't hesitate to come back if you have other questions.

**Comment by kingsleyh** [comment]
Hi - thanks - I have generated using the ed25519 functions but I'm still having a problem making any of the existing js libs work with it. My first choice would be that one of these can work.

either:  https://npm.runkit.com/elliptic
or : https://npm.runkit.com/tweetnacl

would be fine. 

Do these things I've generated with ed25519 look correct?

private_key: d08e3a6f1349adc32cba3613cb5a94ebc01ce4235c4ef62a8634c0fc57c5f219
public_key: 85833672e19366365585ccc499ae84b81c70db9e5aa8df61482e1e07fb3c5067
message: "deadbeef"
signature: dce02302c63a9f826c2e547e6e6e304b7a3936b34dc002325f3fe41b7ad29db17734c41ab4a4e8b795c47a8e5c65090910ef25b48bde48e6edc72d54ead0af03

In the elliptic - it takes the message as a hex - would I have to make a sha-512 out of the message for that one to work?

any help appreciated

Thanks

**Comment by kingsleyh** [comment]
for example pasting this:

```
var EdDSA = require('elliptic').eddsa;
var ec = new EdDSA('ed25519');
var public_key = '85833672e19366365585ccc499ae84b81c70db9e5aa8df61482e1e07fb3c5067';
var key = ec.keyFromPublic(public_key, 'hex');
var message_sha512_hashed = "113a3bc783d851fc0373214b19ea7be9fa3de541ecb9fe026d52c603e8ea19c174cc0e9705f8b90d312212c0c3a6d8453ddfb3e3141409cf4bedc8ef033590b4"

var signature = 'dce02302c63a9f826c2e547e6e6e304b7a3936b34dc002325f3fe41b7ad29db17734c41ab4a4e8b795c47a8e5c65090910ef25b48bde48e6edc72d54ead0af03';

key.verify(message_sha512_hashed, signature)
```

over here:   https://npm.runkit.com/elliptic

fails to verify the signature

**Comment by fscoto** [comment]
Are you sure you're using the API correctly? The following seems to verify correctly for me. Note the change to the `key.verify()` operation.

```js
var EdDSA = require('elliptic').eddsa;
var ec = new EdDSA('ed25519');
var public_key = '85833672e19366365585ccc499ae84b81c70db9e5aa8df61482e1e07fb3c5067';
var key = ec.keyFromPublic(public_key, 'hex');

var signature = 'dce02302c63a9f826c2e547e6e6e304b7a3936b34dc002325f3fe41b7ad29db17734c41ab4a4e8b795c47a8e5c65090910ef25b48bde48e6edc72d54ead0af03';

key.verify(Buffer.from('deadbeef', 'utf8'), signature)
```

**Comment by kingsleyh** [comment]
oh wow you are right!
I was thrown off by the docs saying I had to provide a msg hash

**Comment by kingsleyh** [comment]
Thanks very much for all your help - you have been extremely helpful :) I’ve got everything working that I need now

**Comment by fscoto** [comment]
You're welcome; best of luck with whatever your project might be!

**Comment by kingsleyh** [comment]
since you asked :) - my project is here:  https://sushichain.io - I'm moving from ecdsa and secp256k1 to using this awesome library instead.
