### ISSUE TITLE
MSVC 2019 warnings

### ISSUE THREAD

**Issue by mireiner** [LoupVaillant/Monocypher#179]
Hi there,

for cosmetic reasons you might like to know and fix following MSVC 2019 warnings:

monocypher.c(935,61): warning C4244: "return": conversion from "u64" to "u32", possible loss of data

monocypher.c(1422,1): warning C4267: 'initializing': conversion from "size_t" to "int", possible loss of data

Thank you for this good library!
mireiner

**Comment by LoupVaillant** [comment]
Good catch, thanks! Fixed now.
