### ISSUE TITLE
Explain the purpose of "key" and "ad" in argon

### ISSUE THREAD

**Issue by occivink** [LoupVaillant/Monocypher#18]
Hi,
I like the manual because it's pretty much self-sufficient for a crypto newbie, but it doesn't really explain anything about these two parameters of the argon hash, except that they're optional. 
What is their purpose, and when would you want to use them?

**Comment by LoupVaillant** [comment]
Hmm, the manual may indeed lack a detail or two there.

Technically, those parameters are treated exactly the same way password and salt are treated: they are all hashed together before we do the memory hard stuff. It doesn't even matter which argument you use to put the password and salt, the security is the same.

Conceptually though, `key` and `ad` do serve specific purposes.

* The `key` argument functions like Blake2b's keyed mode. One purpose could be to add some "pepper": a secret key that is global to the password database, but separate from it, and unlikely to leak with it. That way, if your password data base leak, it is useless without the pepper. (Actual pepper would be an encryption key, which has the advantage of being reversible (no need to wait for user login), but easier to screw up (stuff like encryption stream reuse)).

* The `ad` argument stands for "additional data". It's purpose is similar to that of the additional data in AEAD constructions. I can't give any practical examples, though.

If you want to use Monocypher to hash passwords right now, don't bother with `key` and `ad`, they're useless. Just hash the password with a random salt.

---

I can fix the manual, or wait for a pull request. You're welcome to devise one if you want to.

**Comment by CuleX** [comment]
Doesn't look like the PR will be coming anytime soon.

**Comment by occivink** [comment]
Yeah sorry. Thanks @LoupVaillant for the answer, but I don't feel too comfortable writing a paragraph about something that I only have a cursory understanding of.

**Comment by LoupVaillant** [comment]
No problem, I'll take care of it.

**Comment by LoupVaillant** [comment]
Explanation added in the manual, closing this.
