### ISSUE TITLE
MSVC compiler warning (level 4) cosmetic

### ISSUE THREAD

**Issue by mireiner** [LoupVaillant/Monocypher#187]
Hi there,

for cosmetic reason you might like to know and fix following MSVC compiler warning (level 4):

monocypher.c(1846,33): warning C4244: "-=": conversion from "int" to "u8", possible loss of data

Thanks for this very usefull library :-)
mireiner

**Comment by LoupVaillant** [comment]
Oops, right, I should have made the conversion explicit.  
Fixing right away, thanks.
