### ISSUE TITLE
Idiomatic C++ API?

### ISSUE THREAD

**Issue by snej** [LoupVaillant/Monocypher#193]
I've made an idiomatic C++ wrapper around Monocypher. The hashes/keys/nonces are all distinct subclasses of `std::array`, with template parameters for options like sizes and algorithms, making them type-safe. They override `operator==` to perform constant-time comparison, and erase themselves on destruct.

Is this something you'd consider adding to Monocypher itself, or should I publish it as a separate repo?

**Comment by LoupVaillant** [comment]
I thought of making a C++ wrapper for years, never got around to it. I'd be thankful for yours.

Monocypher is C only, though. I'd prefer a separate repository. Ideally, I'd add a link to the [download page](https://monocypher.org/download/) under the language bindings section. Just tell me the canonical link, I'll add it.

**Comment by snej** [comment]
Cool. I will put together the repo and then post the URL here.

**Comment by snej** [comment]
Here it is: https://github.com/snej/monocypher-cpp
API is here: https://github.com/snej/monocypher-cpp/blob/master/include/Monocypher.hh

**Comment by LoupVaillant** [comment]
Excellent, thank you. I've added the link. Hopefully this will send a contributor or two your way. :-)
