### ISSUE TITLE
Minor duplicative lines of code

### ISSUE THREAD

**Issue by TomMD** [LoupVaillant/Monocypher#201]
I see (well, [something sees](https://console.muse.dev/result/TomMD/Monocypher/01ESN14PPQJ3RBW1WPF46FC5JN?type=DEAD_STORE)):

```
    u64 carry = 1;
    carry = 1;
```

Here: https://github.com/LoupVaillant/Monocypher/blob/01277b033c06c6dc4a67d0a15fb0a8a2b48f063a/src/monocypher.c#L1744

**Comment by LoupVaillant** [comment]
My, I must have been tired. Fixing right away, thanks.

**Comment by TomMD** [comment]
If you'd like you can run [muse](https://GitHub.com/apps/muse-dev), and thus infer, on every PR. It will comment on such bugs.

**Comment by LoupVaillant** [comment]
This tool looks interesting indeed. I will take a look, thanks.

**Comment by tankf33der** [comment]
I confirm `infer` can warning this and `gcc -fanalyzer` cant.
