### ISSUE TITLE
Certificate for https://monocypher.org expired the 12th

### ISSUE THREAD

**Issue by brycx** [LoupVaillant/Monocypher#208]
The certificate seems to have expired on the 12th. I don't know the details of the setup for the site, but Let's Encrypt has the Certbot tool which can automate renewal if that's something that's possible to setup for the domain.

![expired_monocypher_cert](https://user-images.githubusercontent.com/34031846/111063235-ba9d1f00-84ad-11eb-8199-c254fbe599ea.png)

**Comment by LoupVaillant** [comment]
Crap, my bad.
I failed at automation, sorry.
Will sort this out ASAP.

**Comment by LoupVaillant** [comment]
Should be fixed now. I *did* have a cron job setup, but it was a copy paste hack job that depended on Python, which wasn't installed… This is now fixed, and the certificate has been renewed. It should work now.

Thanks for letting me know,
Loup.
