### ISSUE TITLE
Weird spacing in the manual

### ISSUE THREAD

**Issue by mikejsavage** [LoupVaillant/Monocypher#217]
There's no spacing above the description header, which looks wonky with how much the function prototypes are spaced out. e.g.:

![image](https://user-images.githubusercontent.com/579299/126227741-3840de29-d0cc-47a0-82b3-5a76515a6048.png)

If you add some margin-top to h1 it cleans it up a bit

**Comment by LoupVaillant** [comment]
Indeed that's weird. Should be fixed now, thanks.
