### ISSUE TITLE
Any equivalent of Sodium's `crypto_scalarmult`?

### ISSUE THREAD

**Issue by snej** [LoupVaillant/Monocypher#229]
To [reimplement SecretHandshake with Monocypher](https://github.com/snej/secret-handshake-capnp/issues/2), it looks like I'd need an equivalent of libSodium's [`crypto_scalarmult`](https://libsodium.gitbook.io/doc/advanced/scalar_multiplication#usage) function. Monocypher doesn't seem to expose anything similar, and I know little about elliptic curves so I can't tell if there's something comparable buried inside the code. Any ideas?

**Comment by snej** [comment]
FYI, the Secret Handshake algorithm is described in [this paper](http://dominictarr.github.io/secret-handshake-paper/shs.pdf), pp.9-11. The synopsis is:

<img width="508" alt="Screen Shot 2022-02-01 at 11 48 00 AM" src="https://user-images.githubusercontent.com/43241/152040594-d783bd48-b3ee-467b-b4d9-6f92936ddabd.png">

I assume the "_a . b_" parts are where `crypto_scalarmult` comes in.

**Comment by fscoto** [comment]
This is untested, but seems like it should check out:

Monocypher's `crypto_x25519` *should* be completely compatible with `crypto_scalarmult`. Monocypher's `crypto_x25519_public_key` *should* be completely compatible with `crypto_scalarmult_base`. Give it a quick test with random values.

**Comment by LoupVaillant** [comment]
I can confirm that:

* Monocypher's `crypto_x25519()` is compatible with Libsodium's `crypto_scalarmult()`
* Monocypher's `crypto_x25519_public_key` is compatible with `crypto_scalarmult_base()`

As @fscoto noted, this compatibility is enforced by the test suite.

Libsodium and Monocypher have different philosophies for naming, hence the name difference: I went with describing the official name of the primitive whenever applicable, while Libsodium went with "higher level" sounding names whenever applicable.

**Comment by snej** [comment]
Thanks!
