### ISSUE TITLE
Timing tests are too strict

### ISSUE THREAD

**Issue by LoupVaillant** [LoupVaillant/Monocypher#25]
Reported by  /u/knotdjb on reddit.

Timing tests for constant time comparison fail on some machines. To reproduce, just run:

    $ make self
    $ ./self

It might or might not fail.

We could make the threshold more tolerant, or take several measurements (the same way we do for the speed benchmark), or be a little cleverer, and compare against a variable time comparison.

**Comment by CuleX** [comment]
> make the threshold more tolerant

I've had trouble determining the threshold in the first place. `clock()` is definitely not very accurate, but there are no reasonable alternatives in sight.

> take several measurements

Maybe.

> be a little cleverer, and compare against a variable time comparison

We have no guarantee that `memcmp()` *is* variable-time, though I guess that could be trivially manually implemented. However, we'd still have the same issue: What's the threshold? There's no way to get a theoretical minimal value.

Though personally, I'm in favor of the comparison against known variable-time comparison.

**Comment by LoupVaillant** [comment]
Turned out the tests indicated a potential vulnerability where `crypto_memcmp()` did not, in fact, run in constant time. This has since been fixed by changing the API. We now use `crypto_verify16()`, `crypto_verify32()`, and `crypto_verify64()`.
