### ISSUE TITLE
Clarify crypto_x25512 function

### ISSUE THREAD

**Issue by xobs** [LoupVaillant/Monocypher#260]
The example function for `crypto_x25519()` contains the following:

https://github.com/LoupVaillant/Monocypher/blob/014f45d9fe54271c8e08006eea83fa97b9d55d32/doc/crypto_x25519.3monocypher#L187-L195

Specifically, there's this line:

https://github.com/LoupVaillant/Monocypher/blob/014f45d9fe54271c8e08006eea83fa97b9d55d32/doc/crypto_x25519.3monocypher#L192

However, the function `crypto_x25512()` doesn't appear to exist anywhere.

Should this function be filled in by the user, or is it a typo? Or is this meant to be `crypto_x25519_public_key()`?

**Comment by LoupVaillant** [comment]
Woops, good catch, I must have been drunk on sleep deprivation. It should be `crypto_x25519_public_key()` indeed. Will correct ASAP, thanks for the report.
