### ISSUE TITLE
Monocypher in Java?

### ISSUE THREAD

**Issue by BigPanda97** [LoupVaillant/Monocypher#272]
Is there any Java Wrapper / JNI for Monocypher available? (Like LazySodium for libSodium etc.)?

And if not, is it at least planned for the future? Java is one of the most common programming languages...

**Comment by LoupVaillant** [comment]
On the [official download page](https://monocypher.org/download/) there are a number of third party language bindings, is this what you are talking about? There is no plan at the moment to do these myself, but I do try to keep track of third party language bindings & distributions.

**Comment by BigPanda97** [comment]
Yes, that's what I meant. I searched through GitHub and Google, but I couldn't find any binding for Java. However, Java is one of the most common programming languages, and especially needed for Android. So it is really really pity, that a Java binding for Monocypher is missing.

**Comment by LoupVaillant** [comment]
Oops, I missed "Java", and only saw "JNI", which I didn't even recognise.

Yeah, sorry about that. I'm really out of touch with Java (I did some in college back when it didn't even have generics), so those bindings are out of scope. If you know how to use Java's FFI however you could make your own. I would gladly add it to the list even if it's incomplete.
