### ISSUE TITLE
Dead links in the README.md file

### ISSUE THREAD

**Issue by antonfors** [LoupVaillant/Monocypher#280]
Hello!

I just noticed a minor non-functional issue which can impact how the project is perceived:

There are two dead links in the README.md that seem to have simply not been updated when the manual was updated at some point:

1. The BLAKE2b link, which currently links to https://monocypher.org/manual/blake2 but should link to https://monocypher.org/manual/blake2b.
2. The SHA-512 link, which currently links to https://monocypher.org/manual/sha-512 but should link to https://monocypher.org/manual/sha512.

Furthermore the TrustInSoft CI badge seems broken, although I cannot judge whether this is a temporary issue on their end or whether some action needs to be taken by the Monocypher project.

**Comment by LoupVaillant** [comment]
Hi, thanks for the heads up.

The links are now fixed. The badge… is kinda routinely down, it's not really on us. I do anticipate however that one day TIS-CI may go down for good, in which case I'll have to remove the badge.
