### ISSUE TITLE
Add comment about generating vectors.h in dist/README.md

### ISSUE THREAD

**Issue by secworks** [LoupVaillant/Monocypher#36]
Aloha!

I would suggest pointing to, or adding a comment like "remember to generate the test vectors and the file vectors.h, see XYZ" in dist/README.md under the "make test" info. The need for generating the vectors are described in the top level README.md, but is worth repeating in the dist/README.md to not confuse those that gets surprised when following the "make test" instruction in the dist/README.md.

**Comment by LoupVaillant** [comment]
Actually, the test vectors will be provided in the tarball releases. The end users won't have to generate it at all. That was the whole point of generating vectors in the first place: making tests that don't need libsodium. I used to have direct comparison tests, but I scrapped them in favour of those generated vectors.

On the other hand, you're right. Which is why I added a note that triggers whenever a user tries to `make test` without `vectors.h`. So, fixed!

By the way, I removed the `dist/` directory, it was confusing things for no tangible benefit. I thought it would facilitate tarball generation, but then it turned out that writing a tarball generation script is easy (hint: use the `-X` option from GNU tar).

**Comment by secworks** [comment]
Sounds good, albeit no note triggered when I ran the compilation. Simply having a ready made vectors.h sounds to me the way forward.

**Comment by LoupVaillant** [comment]
The note only triggers when you don't have `vectors.h`. This is so end users aren't bothered.

If however you delete `tests/vectors.h` and *still* can't trigger the note, I have a bug.

I'm reluctant to push vectors.h to the repository, because (i) it's a generated file, and (ii) it weights 4.2Mb.

**Comment by secworks** [comment]
No, it did'nt trigger. I just got std Makefile "no rule to make...." due to missing vectors.h

4.2 Mbit isn't much. 4.2MByte isn't that much either. It is a text file and will be compressed during transfer. And adding a generated file is imho fine. It makes life easier for the users.

**Comment by CuleX** [comment]
4.2 MB isn't nothing. See [this story](http://blog.chriszacharias.com/page-weight-matters) on why even these kinds of sizes matters.

**Comment by secworks** [comment]
Ok, where to start.

First off, that page talks about problems with YT and their pages. YT pages are literally sent 100k/s to users all over the world. Many users also download those pages many times. What we are discussing here is a single file in a Git repo for a crypto lib. How many times do you think vectors.h will be sent/s? Number of times to a user will clone the repo? Monocypher is a fine piece of code, but I don't think it will rival the latest cad vid on YT.

Secondly, AFAIK git will actually perform basically gzip compression on blobs when cloning the repo. The vectors.h file when compressed is 974 kB. If size really is an issue, add a compressed version of the file and call gzip -d from the Makefile. Ugly but works too. The good thing of adding the vectors.h is (AFAIK) that the dependency on libsodium can be removed. If so I would suggest moving the test vector generation to a separate repo.

**Comment by LoupVaillant** [comment]
> No, it did'nt trigger. I just got std Makefile "no rule to make...." due to missing vectors.h

Wait what? How is that even possible? There *is* a `tests/vectors.h:` rule. Open the makefile, you should see a bunch of `@echo`. Now if the rule is there and the message *still* doesn't print, I have to know what version of make you are using so I can reproduce that very odd bug.

---

The main problem with `vectors.h` isn't its size, it's its stability. It is liable to change quite a bit whenever there's the slightest change in their generation. I also hate the idea of putting generated files in the repo.

It *will* be included in all future tarballs, though.

**Comment by secworks** [comment]
You committed that echo-structure after I posted this issue.
https://github.com/LoupVaillant/Monocypher/commit/164d7de5531256a10f464bd8ba56831f3ec7e46c#diff-cd5dbf3629c558b0104ba8f0937d6816

**Comment by secworks** [comment]
When I tested it, that wasn't there.

**Comment by LoupVaillant** [comment]
Ah sorry, I may not have pushed that commit when I closed this issue.

**Comment by LoupVaillant** [comment]
For the record, I recently changed the random number generation (since I didn't aim to be secure, I opted for something much simpler, that didn't depend on Monocypher to run). Thus, the test vectors completely changed. Not putting them in the repo saved 4.2Mb times two. :smile_cat:
