### ISSUE TITLE
Seen these warnings?

### ISSUE THREAD

**Issue by secworks** [LoupVaillant/Monocypher#37]
Aloha!

Did a "make test" and clang/llvm emitted a number of warnings on test.c:
tests/test.c:237:12: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
    d = (d < 0 ? -d : d);
         ~ ^ ~
tests/test.c:254:12: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
    d = (d < 0 ? -d : d);
         ~ ^ ~
tests/test.c:274:25: warning: variable length array folded to constant array as an extension [-Wgnu-folding-constant]
        u8 output_chunk[input_size];
                        ^~~~~~~~~~
tests/test.c:275:25: warning: variable length array folded to constant array as an extension [-Wgnu-folding-constant]
        u8 output_whole[input_size];
                        ^~~~~~~~~~
tests/test.c:277:25: warning: variable length array folded to constant array as an extension [-Wgnu-folding-constant]
        u8 input       [input_size];  p_random(input, input_size);
                        ^~~~~~~~~~
tests/test.c:308:24: warning: variable length array folded to constant array as an extension [-Wgnu-folding-constant]
        u8 output_part[stream_size    ];
                       ^~~~~~~~~~~
tests/test.c:309:24: warning: variable length array folded to constant array as an extension [-Wgnu-folding-constant]
        u8 output_all [stream_size    ];
                       ^~~~~~~~~~~
tests/test.c:310:24: warning: variable length array folded to constant array as an extension [-Wgnu-folding-constant]
        u8 output_more[stream_size * 2];
                       ^~~~~~~~~~~~~~~
tests/test.c:357:18: warning: variable length array folded to constant array as an extension [-Wgnu-folding-constant]
        u8 input[input_size];  p_random(input, input_size);
                 ^~~~~~~~~~
tests/test.c:398:18: warning: variable length array folded to constant array as an extension [-Wgnu-folding-constant]
        u8 input[input_size];  p_random(input, input_size);
                 ^~~~~~~~~~
tests/test.c:436:18: warning: variable length array folded to constant array as an extension [-Wgnu-folding-constant]
        u8 input[input_size];  p_random(input, input_size);
                 ^~~~~~~~~~
tests/test.c:466:16: warning: variable length array folded to constant array as an extension [-Wgnu-folding-constant]
    u8 message[message_size];  p_random(message, 32);
               ^~~~~~~~~~~~

This is with gcc aliased to clang Apple LLVM version 9.0.0 (clang-900.0.37).

Have you seen these before?

**Comment by CuleX** [comment]
>  tests/test.c:237:12: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]

As for those, yes, I've seen them before on some platforms. This is because `clock_t` (returned by `clock(3)`) is not guaranteed to be unsigned. On your platform, that ternary is always false, but on others it might not be.

The others are new to me but should *probably* be addressed.

**Comment by LoupVaillant** [comment]
Wait a minute, I've just checked the C11 standard, and it says `clock_t` is supposed to be a `size_t`. *Everyone* should have those warnings! Oh well. At least I know the width of this stuff: I can now convert it to size_t, and check if it's more than 2^(sizeof(size_t)*8 -1) -1 (if we don't have 8 bit bytes, I give up).

The folded arrays are easy to fix with the help of the pre-procesor. But those are static constants dammit, the arrays are *not* variable length.  What are you compiling the tests with?

**Comment by LoupVaillant** [comment]
I just tried to suppress the variable length array warnings. Does that work?

**Comment by CuleX** [comment]
> Wait a minute, I've just checked the C11 standard, and it says `clock_t` is supposed to be a `size_t`. *Everyone* should have those warnings! Oh well. At least I know the width of this stuff: I can now convert it to size_t, and check if it's more than 2^(sizeof(size_t)*8 -1) -1 (if we don't have 8 bit bytes, I give up).

Are you talking about n1570, § 7.27.1 no. 3? If so, it reads for me:

> 3 The types declared are `size_t` (described in 7.19);
> `clock_t`
> and
> `time_t`
> which are real types capable of representing times; [...]

I don't think that means what you think it means. I interpret that like this:

* `<time.h>` declares:
  * `size_t`, as per 7.19,
  * `clock_t`, a real type capable of representing times,
  * `time_t`, a real type capable of representing times

Even if your interpretation were right, [the real world very much disagrees](https://stackoverflow.com/a/17190680), at least on Linux/glibc and [musl on any platform that doesn't provide `clock_t`](https://git.musl-libc.org/cgit/musl/tree/include/alltypes.h.in#n36).

**Comment by secworks** [comment]
LoupVaillant: See my original posting, I'm using the latest clang released by Apple in thir CLI tools.

On MacOS clock_t is a typedef for __darwin_clock_t which is a typedef for unsigned long.

**Comment by secworks** [comment]
Pulling your update and recompiling. I get:

gcc -std=gnu99  -pedantic -Wall -Wextra -O3 -march=native -I src -fPIC -c -o lib/test.o tests/test.c
tests/test.c:505:16: warning: variable length array folded to constant array as an extension [-Wgnu-folding-constant]
    u8 message[message_size];  p_random(message, 32);
               ^~~~~~~~~~~~
1 warning generated.

So almost all gone.

**Comment by LoupVaillant** [comment]
@CuleX, you're right, I read that section wrong.

@secworks, thanks, I'll fix that last one.
