### ISSUE TITLE
Ginormous, impossible to review assembly output for constant time comparison functions

### ISSUE THREAD

**Issue by LoupVaillant** [LoupVaillant/Monocypher#38]
Tested with GCC 5.4.0, -O3 optimisations. Upon noticing suspect timings for some usages of `crypto_memcmp()`, I tried to look at the assembly output. I got this hard to review mess:

    .LCOLDB18:
	.text
    .LHOTB18:
    	.p2align 4,,15
    	.globl	crypto_memcmp
    	.type	crypto_memcmp, @function
    crypto_memcmp:
    .LFB11:
    	.cfi_startproc
    	testq	%rdx, %rdx
    	pushq	%r12
    	.cfi_def_cfa_offset 16
    	.cfi_offset 12, -16
    	pushq	%rbp
    	.cfi_def_cfa_offset 24
    	.cfi_offset 6, -24
    	pushq	%rbx
    	.cfi_def_cfa_offset 32
    	.cfi_offset 3, -32
    	je	.L174
    	movq	%rdi, %r8
    	negq	%r8
    	andl	$15, %r8d
    	cmpq	%rdx, %r8
    	cmova	%rdx, %r8
    	cmpq	$17, %rdx
    	ja	.L197
    	movq	%rdx, %r8
    .L164:
    	movzbl	(%rdi), %ecx
    	xorb	(%rsi), %cl
    	cmpq	$1, %r8
    	movzbl	%cl, %eax
    	je	.L177
    	movzbl	1(%rdi), %eax
    	xorb	1(%rsi), %al
    	orl	%eax, %ecx
    	cmpq	$2, %r8
    	movzbl	%cl, %eax
    	je	.L178
    	movzbl	2(%rdi), %eax
    	xorb	2(%rsi), %al
    	orl	%eax, %ecx
    	cmpq	$3, %r8
    	movzbl	%cl, %eax
    	je	.L179
    	movzbl	3(%rdi), %eax
    	xorb	3(%rsi), %al
    	orl	%eax, %ecx
    	cmpq	$4, %r8
    	movzbl	%cl, %eax
    	je	.L180
    	movzbl	4(%rdi), %eax
    	xorb	4(%rsi), %al
    	orl	%eax, %ecx
    	cmpq	$5, %r8
    	movzbl	%cl, %eax
    	je	.L181
    	movzbl	5(%rdi), %eax
    	xorb	5(%rsi), %al
    	orl	%eax, %ecx
    	cmpq	$6, %r8
    	movzbl	%cl, %eax
    	je	.L182
    	movzbl	6(%rdi), %eax
    	xorb	6(%rsi), %al
    	orl	%eax, %ecx
    	cmpq	$7, %r8
    	movzbl	%cl, %eax
    	je	.L183
    	movzbl	7(%rdi), %eax
    	xorb	7(%rsi), %al
    	orl	%eax, %ecx
    	cmpq	$8, %r8
    	movzbl	%cl, %eax
    	je	.L184
    	movzbl	8(%rdi), %eax
    	xorb	8(%rsi), %al
    	orl	%eax, %ecx
    	cmpq	$9, %r8
    	movzbl	%cl, %eax
    	je	.L185
    	movzbl	9(%rdi), %eax
    	xorb	9(%rsi), %al
    	orl	%eax, %ecx
    	cmpq	$10, %r8
    	movzbl	%cl, %eax
    	je	.L186
    	movzbl	10(%rdi), %eax
    	xorb	10(%rsi), %al
    	orl	%eax, %ecx
    	cmpq	$11, %r8
    	movzbl	%cl, %eax
    	je	.L187
    	movzbl	11(%rdi), %eax
    	xorb	11(%rsi), %al
    	orl	%eax, %ecx
    	cmpq	$12, %r8
    	movzbl	%cl, %eax
    	je	.L188
    	movzbl	12(%rdi), %eax
    	xorb	12(%rsi), %al
    	orl	%eax, %ecx
    	cmpq	$13, %r8
    	movzbl	%cl, %eax
    	je	.L189
    	movzbl	13(%rdi), %eax
    	xorb	13(%rsi), %al
    	orl	%eax, %ecx
    	cmpq	$14, %r8
    	movzbl	%cl, %eax
    	je	.L190
    	movzbl	14(%rdi), %eax
    	xorb	14(%rsi), %al
    	orl	%eax, %ecx
    	cmpq	$15, %r8
    	movzbl	%cl, %eax
    	je	.L191
    	movzbl	15(%rdi), %eax
    	xorb	15(%rsi), %al
    	orl	%eax, %ecx
    	cmpq	$17, %r8
    	movzbl	%cl, %eax
    	jne	.L192
    	movzbl	16(%rsi), %eax
    	xorb	16(%rdi), %al
    	orl	%eax, %ecx
    	movzbl	%cl, %eax
    	movl	$17, %ecx
    .L166:
    	cmpq	%r8, %rdx
    	je	.L167
    .L165:
    	movq	%rdx, %r11
    	leaq	-1(%rdx), %r10
    	subq	%r8, %r11
    	leaq	-16(%r11), %r9
    	subq	%r8, %r10
    	shrq	$4, %r9
    	addq	$1, %r9
    	movq	%r9, %rbx
    	salq	$4, %rbx
    	cmpq	$14, %r10
    	jbe	.L168
    	pxor	%xmm1, %xmm1
    	leaq	(%rdi,%r8), %r12
    	xorl	%r10d, %r10d
    	pxor	%xmm5, %xmm5
    	addq	%rsi, %r8
    	pxor	%xmm2, %xmm2
    	xorl	%ebp, %ebp
    .L169:
    	movdqu	(%r8,%r10), %xmm0
    	addq	$1, %rbp
    	pxor	(%r12,%r10), %xmm0
    	addq	$16, %r10
    	cmpq	%rbp, %r9
    	movdqa	%xmm0, %xmm3
    	punpckhbw	%xmm5, %xmm0
    	punpcklbw	%xmm5, %xmm3
    	movdqa	%xmm3, %xmm4
    	punpckhwd	%xmm2, %xmm3
    	punpcklwd	%xmm2, %xmm4
    	por	%xmm4, %xmm3
    	movdqa	%xmm0, %xmm4
    	punpckhwd	%xmm2, %xmm0
    	punpcklwd	%xmm2, %xmm4
    	por	%xmm4, %xmm3
    	por	%xmm3, %xmm0
    	por	%xmm0, %xmm1
    	ja	.L169
    	movdqa	%xmm1, %xmm0
    	addq	%rbx, %rcx
    	psrldq	$8, %xmm0
    	por	%xmm1, %xmm0
    	movdqa	%xmm0, %xmm1
    	psrldq	$4, %xmm1
    	por	%xmm1, %xmm0
    	movd	%xmm0, %r8d
    	orl	%r8d, %eax
    	cmpq	%r11, %rbx
    	je	.L167
    .L168:
    	movzbl	(%rsi,%rcx), %r8d
    	xorb	(%rdi,%rcx), %r8b
    	movzbl	%r8b, %r8d
    	orl	%r8d, %eax
    	leaq	1(%rcx), %r8
    	cmpq	%r8, %rdx
    	jbe	.L167
    	movzbl	1(%rdi,%rcx), %r8d
    	xorb	1(%rsi,%rcx), %r8b
    	movzbl	%r8b, %r8d
    	orl	%r8d, %eax
    	leaq	2(%rcx), %r8
    	cmpq	%r8, %rdx
    	jbe	.L167
    	movzbl	2(%rdi,%rcx), %r8d
    	xorb	2(%rsi,%rcx), %r8b
    	movzbl	%r8b, %r8d
    	orl	%r8d, %eax
    	leaq	3(%rcx), %r8
    	cmpq	%r8, %rdx
    	jbe	.L167
    	movzbl	3(%rdi,%rcx), %r8d
    	xorb	3(%rsi,%rcx), %r8b
    	movzbl	%r8b, %r8d
    	orl	%r8d, %eax
    	leaq	4(%rcx), %r8
    	cmpq	%r8, %rdx
    	jbe	.L167
    	movzbl	4(%rdi,%rcx), %r8d
    	xorb	4(%rsi,%rcx), %r8b
    	movzbl	%r8b, %r8d
    	orl	%r8d, %eax
    	leaq	5(%rcx), %r8
    	cmpq	%r8, %rdx
    	jbe	.L167
    	movzbl	5(%rdi,%rcx), %r8d
    	xorb	5(%rsi,%rcx), %r8b
    	movzbl	%r8b, %r8d
    	orl	%r8d, %eax
    	leaq	6(%rcx), %r8
    	cmpq	%r8, %rdx
    	jbe	.L167
    	movzbl	6(%rdi,%rcx), %r8d
    	xorb	6(%rsi,%rcx), %r8b
    	movzbl	%r8b, %r8d
    	orl	%r8d, %eax
    	leaq	7(%rcx), %r8
    	cmpq	%r8, %rdx
    	jbe	.L167
    	movzbl	7(%rdi,%rcx), %r8d
    	xorb	7(%rsi,%rcx), %r8b
    	movzbl	%r8b, %r8d
    	orl	%r8d, %eax
    	leaq	8(%rcx), %r8
    	cmpq	%r8, %rdx
    	jbe	.L167
    	movzbl	8(%rdi,%rcx), %r8d
    	xorb	8(%rsi,%rcx), %r8b
    	movzbl	%r8b, %r8d
    	orl	%r8d, %eax
    	leaq	9(%rcx), %r8
    	cmpq	%r8, %rdx
    	jbe	.L167
    	movzbl	9(%rdi,%rcx), %r8d
    	xorb	9(%rsi,%rcx), %r8b
    	movzbl	%r8b, %r8d
    	orl	%r8d, %eax
    	leaq	10(%rcx), %r8
    	cmpq	%r8, %rdx
    	jbe	.L167
    	movzbl	10(%rdi,%rcx), %r8d
    	xorb	10(%rsi,%rcx), %r8b
    	movzbl	%r8b, %r8d
    	orl	%r8d, %eax
    	leaq	11(%rcx), %r8
    	cmpq	%r8, %rdx
    	jbe	.L167
    	movzbl	11(%rdi,%rcx), %r8d
    	xorb	11(%rsi,%rcx), %r8b
    	movzbl	%r8b, %r8d
    	orl	%r8d, %eax
    	leaq	12(%rcx), %r8
    	cmpq	%r8, %rdx
    	jbe	.L167
    	movzbl	12(%rdi,%rcx), %r8d
    	xorb	12(%rsi,%rcx), %r8b
    	movzbl	%r8b, %r8d
    	orl	%r8d, %eax
    	leaq	13(%rcx), %r8
    	cmpq	%r8, %rdx
    	jbe	.L167
    	movzbl	13(%rdi,%rcx), %r8d
    	xorb	13(%rsi,%rcx), %r8b
    	movzbl	%r8b, %r8d
    	orl	%r8d, %eax
    	leaq	14(%rcx), %r8
    	cmpq	%r8, %rdx
    	jbe	.L167
    	movzbl	14(%rsi,%rcx), %edx
    	xorb	14(%rdi,%rcx), %dl
    	movzbl	%dl, %edx
    	orl	%edx, %eax
    .L167:
    	subl	$1, %eax
    	shrl	$8, %eax
    	andl	$1, %eax
    	subl	$1, %eax
    .L163:
    	popq	%rbx
    	.cfi_remember_state
    	.cfi_def_cfa_offset 24
    	popq	%rbp
    	.cfi_def_cfa_offset 16
    	popq	%r12
    	.cfi_def_cfa_offset 8
    	ret
    	.p2align 4,,10
    	.p2align 3
    .L197:
    	.cfi_restore_state
    	testq	%r8, %r8
    	jne	.L164
    	xorl	%ecx, %ecx
    	xorl	%eax, %eax
    	jmp	.L165
    	.p2align 4,,10
    	.p2align 3
    .L174:
    	xorl	%eax, %eax
    	jmp	.L163
    	.p2align 4,,10
    	.p2align 3
    .L183:
    	movl	$7, %ecx
    	jmp	.L166
    	.p2align 4,,10
    	.p2align 3
    .L184:
    	movl	$8, %ecx
    	jmp	.L166
    	.p2align 4,,10
    	.p2align 3
    .L185:
    	movl	$9, %ecx
    	jmp	.L166
    	.p2align 4,,10
    	.p2align 3
    .L186:
    	movl	$10, %ecx
    	jmp	.L166
    	.p2align 4,,10
    	.p2align 3
    .L187:
    	movl	$11, %ecx
    	jmp	.L166
    	.p2align 4,,10
    	.p2align 3
    .L188:
    	movl	$12, %ecx
    	jmp	.L166
    	.p2align 4,,10
    	.p2align 3
    .L189:
    	movl	$13, %ecx
    	jmp	.L166
    	.p2align 4,,10
    	.p2align 3
    .L190:
    	movl	$14, %ecx
    	jmp	.L166
    	.p2align 4,,10
    	.p2align 3
    .L179:
    	movl	$3, %ecx
    	jmp	.L166
    	.p2align 4,,10
    	.p2align 3
    .L180:
    	movl	$4, %ecx
    	jmp	.L166
    	.p2align 4,,10
    	.p2align 3
    .L181:
    	movl	$5, %ecx
    	jmp	.L166
    	.p2align 4,,10
    	.p2align 3
    .L182:
    	movl	$6, %ecx
    	jmp	.L166
    	.p2align 4,,10
    	.p2align 3
    .L177:
    	movl	$1, %ecx
    	jmp	.L166
    	.p2align 4,,10
    	.p2align 3
    .L178:
    	movl	$2, %ecx
    	jmp	.L166
    	.p2align 4,,10
    	.p2align 3
    .L191:
    	movl	$15, %ecx
    	jmp	.L166
    	.p2align 4,,10
    	.p2align 3
    .L192:
    	movl	$16, %ecx
    	jmp	.L166
    	.cfi_endproc

`crypto_zerocmp()` is just as gigantic:

    .LHOTB19:
    	.p2align 4,,15
    	.globl	crypto_zerocmp
    	.type	crypto_zerocmp, @function
    crypto_zerocmp:
    .LFB12:
    	.cfi_startproc
    	testq	%rsi, %rsi
    	je	.L210
    	movq	%rdi, %rdx
    	movq	%rsi, %rcx
    	negq	%rdx
    	andl	$15, %edx
    	cmpq	%rsi, %rdx
    	cmova	%rsi, %rdx
    	cmpq	$19, %rsi
    	ja	.L217
    .L200:
    	xorl	%edx, %edx
    	xorl	%eax, %eax
    	.p2align 4,,10
    	.p2align 3
    .L202:
    	movzbl	(%rdi,%rdx), %r8d
    	addq	$1, %rdx
    	orl	%r8d, %eax
    	cmpq	%rcx, %rdx
    	jne	.L202
    	cmpq	%rcx, %rsi
    	movq	%rcx, %rdx
    	je	.L203
    .L201:
    	movq	%rsi, %r10
    	leaq	-1(%rsi), %r9
    	subq	%rdx, %r10
    	leaq	-16(%r10), %r8
    	subq	%rdx, %r9
    	shrq	$4, %r8
    	addq	$1, %r8
    	movq	%r8, %r11
    	salq	$4, %r11
    	cmpq	$14, %r9
    	jbe	.L204
    	pxor	%xmm1, %xmm1
    	addq	%rdi, %rdx
    	xorl	%r9d, %r9d
    	pxor	%xmm5, %xmm5
    	pxor	%xmm2, %xmm2
    .L205:
    	movdqa	(%rdx), %xmm0
    	addq	$1, %r9
    	addq	$16, %rdx
    	cmpq	%r9, %r8
    	movdqa	%xmm0, %xmm3
    	punpckhbw	%xmm5, %xmm0
    	punpcklbw	%xmm5, %xmm3
    	movdqa	%xmm3, %xmm4
    	punpckhwd	%xmm2, %xmm3
    	punpcklwd	%xmm2, %xmm4
    	por	%xmm4, %xmm3
    	movdqa	%xmm0, %xmm4
    	punpckhwd	%xmm2, %xmm0
    	punpcklwd	%xmm2, %xmm4
    	por	%xmm4, %xmm3
    	por	%xmm3, %xmm0
    	por	%xmm0, %xmm1
    	ja	.L205
    	movdqa	%xmm1, %xmm0
    	addq	%r11, %rcx
    	psrldq	$8, %xmm0
    	por	%xmm1, %xmm0
    	movdqa	%xmm0, %xmm1
    	psrldq	$4, %xmm1
    	por	%xmm1, %xmm0
    	movd	%xmm0, %edx
    	orl	%edx, %eax
    	cmpq	%r11, %r10
    	je	.L203
    .L204:
    	movzbl	(%rdi,%rcx), %edx
    	orl	%edx, %eax
    	leaq	1(%rcx), %rdx
    	cmpq	%rdx, %rsi
    	jbe	.L203
    	movzbl	1(%rdi,%rcx), %edx
    	orl	%edx, %eax
    	leaq	2(%rcx), %rdx
    	cmpq	%rdx, %rsi
    	jbe	.L203
    	movzbl	2(%rdi,%rcx), %edx
    	orl	%edx, %eax
    	leaq	3(%rcx), %rdx
    	cmpq	%rdx, %rsi
    	jbe	.L203
    	movzbl	3(%rdi,%rcx), %edx
    	orl	%edx, %eax
    	leaq	4(%rcx), %rdx
    	cmpq	%rdx, %rsi
    	jbe	.L203
    	movzbl	4(%rdi,%rcx), %edx
    	orl	%edx, %eax
    	leaq	5(%rcx), %rdx
    	cmpq	%rdx, %rsi
    	jbe	.L203
    	movzbl	5(%rdi,%rcx), %edx
    	orl	%edx, %eax
    	leaq	6(%rcx), %rdx
    	cmpq	%rdx, %rsi
    	jbe	.L203
    	movzbl	6(%rdi,%rcx), %edx
    	orl	%edx, %eax
    	leaq	7(%rcx), %rdx
    	cmpq	%rdx, %rsi
    	jbe	.L203
    	movzbl	7(%rdi,%rcx), %edx
    	orl	%edx, %eax
    	leaq	8(%rcx), %rdx
    	cmpq	%rdx, %rsi
    	jbe	.L203
    	movzbl	8(%rdi,%rcx), %edx
    	orl	%edx, %eax
    	leaq	9(%rcx), %rdx
    	cmpq	%rdx, %rsi
    	jbe	.L203
    	movzbl	9(%rdi,%rcx), %edx
    	orl	%edx, %eax
    	leaq	10(%rcx), %rdx
    	cmpq	%rdx, %rsi
    	jbe	.L203
    	movzbl	10(%rdi,%rcx), %edx
    	orl	%edx, %eax
    	leaq	11(%rcx), %rdx
    	cmpq	%rdx, %rsi
    	jbe	.L203
    	movzbl	11(%rdi,%rcx), %edx
    	orl	%edx, %eax
    	leaq	12(%rcx), %rdx
    	cmpq	%rdx, %rsi
    	jbe	.L203
    	movzbl	12(%rdi,%rcx), %edx
    	orl	%edx, %eax
    	leaq	13(%rcx), %rdx
    	cmpq	%rdx, %rsi
    	jbe	.L203
    	movzbl	13(%rdi,%rcx), %edx
    	orl	%edx, %eax
    	leaq	14(%rcx), %rdx
    	cmpq	%rdx, %rsi
    	jbe	.L203
    	movzbl	14(%rdi,%rcx), %edx
    	orl	%edx, %eax
    .L203:
    	subl	$1, %eax
    	shrl	$8, %eax
    	andl	$1, %eax
    	subl	$1, %eax
    	ret
    	.p2align 4,,10
    	.p2align 3
    .L217:
    	testq	%rdx, %rdx
    	jne	.L218
    	xorl	%ecx, %ecx
    	xorl	%eax, %eax
    	jmp	.L201
    	.p2align 4,,10
    	.p2align 3
    .L210:
    	xorl	%eax, %eax
    	ret
    .L218:
    	movq	%rdx, %rcx
    	jmp	.L200
    	.cfi_endproc
    .LFE12:
    	.size	crypto_zerocmp, .-crypto_zerocmp
    	.section	.text.unlikely

Are those *really* constant time?

**Comment by CuleX** [comment]
Nore for the future reviewer: It's worth keeping [branch prediction](https://stackoverflow.com/a/11227902) in mind.

**Comment by CuleX** [comment]
Update: Regardless of whether the branch predictor caused a noticeable speed difference between random and all-0 output, we're in a bad place. [Attacks based around branch-prediction are a thing](https://eprint.iacr.org/2006/351.pdf).

**Comment by LoupVaillant** [comment]
Well, the code, as designed has only one conditional branch, and it depends on the length of the input, which is not secret. When compiled with `-O2`, the assembly looks as expected: a simple loop, with some bit shuffling inside, and some arithmetic in the end (instead of writing `acc != 0 ? -1 : 0`, we do arithmetic trick that avoid the branch).

Definitely a case of the compiler getting too clever.
