### ISSUE TITLE
crypto_lock_key doesn't exist

### ISSUE THREAD

**Issue by brendanhay** [LoupVaillant/Monocypher#4]
There appears to be a mistake where the [manual](https://github.com/LoupVaillant/Monocypher/blob/f6be933162716a41624976a573465f7b49aaf43d/MANUAL.md#crypto_lock_key) refers to `crypto_lock_key()` which doesn't exist in the header/source, and vice versa `crypto_key_exchange()` exists but is not reflected in the manual.

**Comment by LoupVaillant** [comment]
Oops, I'll correct the manual, thanks.
