### ISSUE TITLE
EdDSA overlap test depends on uninitialized memory

### ISSUE THREAD

**Issue by CuleX** [LoupVaillant/Monocypher#42]
This surfaced as failure when testing on OpenBSD. If the test has been passing until now, it was by coincidence.

https://github.com/LoupVaillant/Monocypher/blob/master/tests/test.c#L621-L627

`input` is `INPUT_SIZE` bytes long, i.e. 160 bytes. `SHA_512_BLOCK_SIZE` is 128 bytes. The routine thus reads 128 bytes from `input + 64`. This overreads `input` at offset 32.

I *suspect* you meant `MESSAGE_SIZE` instead of `SHA_512_BLOCK_SIZE`, but then it'd make no sense to do the multiplication by two in `#define INPUT_SIZE (MESSAGE_SIZE + (2 * 64))`. Due to this uncertainty, I'm reporting this as an issue, rather than creating a pull request.

**Comment by CuleX** [comment]
Fixed by @LoupVaillant in 034afd192923fee314e6aebc7cfcd8103eb21ed4.

**Comment by LoupVaillant** [comment]
Yeah, I only noticed this when I restored the sanitization compilation options, and tried Valgrind. Had I done this earlier, this error wouldn't have made it into production…
