### ISSUE TITLE
Consider renaming or aliasing make test to make check

### ISSUE THREAD

**Issue by CuleX** [LoupVaillant/Monocypher#43]
Currently, the test suite runs with `make test`. automake specifies `make check` that does: ["Run the test suite, if any."](https://www.gnu.org/software/automake/manual/html_node/Standard-Targets.html)

Based on the principle of least surprise, it may be worth renaming or aliasing `make test` to `make check`.

**Comment by LoupVaillant** [comment]
I think aliasing would be best. I don't think the README is worth updating: those who read it will type `make test`, those who don't will be able to try `make check`.

**Comment by LoupVaillant** [comment]
Done!
