### ISSUE TITLE
style.css is installed to man page location

### ISSUE THREAD

**Issue by CuleX** [LoupVaillant/Monocypher#45]
After writing PR #44, I noticed that `style.css` is installed to `$PREFIX/share/man`. That is very likely the wrong place for it.

I see two options:

1. Do not install `style.css`, but that would prevent it from being included in packages, where users *may* want to
2. Put it in `$PREFIX/share/doc/monocypher` and make a note in `README.md`; which will likely get packaged there as well.

**Comment by LoupVaillant** [comment]
Oops, we should go for option 1. The makefile is easily fixed.

The tarball will include a compiled HTML version by the way. Depending how it works, we could even displace the .css into `doc/html` from the beginning.

**Comment by CuleX** [comment]
> The tarball will include a compiled HTML version by the way. Depending how it works, we could even displace the .css into `doc/html` from the beginning.

For the reference, the invocation I use to generate the files:

    mandoc -Oman=%N.%S.html -Ostyle=style.css -Thtml $name.3monocypher > $name.html

Makefiles across directores suck. Suffix rules would pollute `doc/man/man3` again.

**Comment by LoupVaillant** [comment]
Thanks for the command invocation, I'll try that.

> Makefiles across directores suck. Suffix rules would pollute `doc/man/man3` again.

I was just thinking of this little patch:

    install-doc:
    	mkdir -p $(MAN_DIR)
    -	cp -r doc/man/man3/* $(MAN_DIR)
    +	cp -r doc/man/man3/*.3monocypher $(MAN_DIR)

Wouldn't that work?

In any case, I don't think HTML generation belongs to the makefile. I'll write a `build_tarball.sh` script for that (and vector.h generation, and ignoring lots of files…).

**Comment by CuleX** [comment]
That would *work*, yes. It was at that moment I'd realized I shouldn't PR because option 2 might be what you want to do. I assumed it'd be in the makefile because autotools provides `make dist` to make a tarball.

**Comment by LoupVaillant** [comment]
OK, I think I understand.

`make dist` might actually be better, if it doesn't clutter the makefile too much. I'll try that. I'm also realising I'm missing a `make uninstall` target as well…
