### ISSUE TITLE
Profiling test doesn't show the profile

### ISSUE THREAD

**Issue by LoupVaillant** [LoupVaillant/Monocypher#47]
## Steps to reproduce

    $ make clean
    $ make test CC="clang -std=c99" CFLAGS="-fprofile-instr-generate"
    $ tests/coverage.sh

## Observed result

    error: Failed to load coverage: No coverage data found

## Expected result
 
A big fat listing describing code coverage.

## Notes

The `make test` step generates a `default.profraw` file, as expected. The `tests/coverage.sh` just invokes 2 commands:

    llvm-profdata-3.8 merge default.profraw -o all.profdata
    llvm-cov show -instr-profile=all.profdata "./test.out"

The first line generates a `all.profdata`, as expected. The second line is expected to read that file, but for some reason doesn't.

It used to work, so maybe my llvm setup broke upon update or something. But it *could* be that there is indeed a problem with the makefile or the coverage script.

Could someone reproduce this on their machine?

**Comment by CuleX** [comment]
Can reproduce on LLVM 3.8/clang 3.8 as packaged on Debian stable.

Side note: The command is llvm-cov-3.8 instead of llvm-cov for me.

**Comment by LoupVaillant** [comment]
Oops indeed. Thanks, fixing now. I'll also change llvm-cov to llvm-cov-3.8.
