### ISSUE TITLE
Please consider using a free software license

### ISSUE THREAD

**Issue by rain-1** [LoupVaillant/Monocypher#7]
I would recommend <https://directory.fsf.org/wiki/License:ISC> or BSD 3-clause. I think that using a standard free software license will encourage greater adoption of this excellent library!

The current license seems to be some kind of home brew public domain disclaimer. I believe there are some problems with such a license and it doesn't correctly/legally express what you're aiming for with releasing this code <http://www.linuxjournal.com/article/6225>.

**Comment by CuleX** [comment]
ISC or BSD 3-clause would actually modify what the license conveys right now. In particular, they would add constraints about attribution and endorsement.

# Current

For comparison, the current license:

>Copying and distribution of the code, with or without modification, are permitted in any medium without royalty. This code is offered as-is, without any warranty.
>
>(Simply put, do whatever you want with the code. I'm not responsible if anything goes wrong.)

# Attribution

## ISC

> Permission to [...] is granted, provided that the
> above copyright notice and this permission notice appear in all
> copies.

## BSD 3-Clause

> 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
>
> 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

# Endorsement (BSD 3-Clause)

> 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

I'm not sure if that would exclude a note like "Powered by Monocypher" on products and websites.

# Notes

I agree that the current license is a tad clumsy. The article you linked makes a good point. Corporations' legal teams would start sweating bullets when confronted with an off-brand license.

You probably want a lawyer for this, but the current license very decidedly states *nothing on attribution*, whereas ISC or BSD 3-clause do. "Simply put, do whatever you want with the code" implies something akin to granting every imaginable right, including sublicensing and incorporation in a code base without attirbution.

It's important to note that cryptographic code wants to be as free as at all possible to spread. djb seems to routinely attempt to put his code in the public domain. From a quick overview on [Wikipedia/Public_domain_equivalent_license](https://en.wikipedia.org/wiki/Public_domain_equivalent_license), however, there seems to be no satisfying pre-existing equivalent. I doubt that LoupVaillant will want to hire a lawyer to draw a(n attempt at a) proper solution up.

Of course, the decision is not mine to make, but I felt I should point these things out.

**Comment by LoupVaillant** [comment]
My licence come straight from the [GNU all permissive licence](https://www.gnu.org/prep/maintain/html_node/License-Notices-for-Other-Files.html):

> Copying and distribution of this file, with or without modification, are permitted in any medium without royalty provided the copyright notice and this notice are preserved.  This file is offered as-is, without any warranty.

I just removed the attribution part ("provided the copyright notice and this notice are preserved"), and replaced "this file" by "the code". The following note is for clarity only, it is not supposed to be legally binding.

Now that I look at it more closely, I do see one problem: "the code" doesn't include the documentation. I probably should replace it by "source code and documentation" or something, perhaps point the GNU all permissive license?

---

Additionally, I'm willing to consider dual licensing, for instance by adding a CC(0) licence, a 2-clause BSD, or an MIT.

**Comment by CuleX** [comment]
> Now that I look at it more closely, I do see one problem: "the code" doesn't include the documentation. I probably should replace it by "source code and documentation" or something, perhaps point the GNU all permissive license?

I'd at least point that out somewhere in the license file. It may be relevant for interpretation.

Dual licensing sounds like it'd be a workable solution. The CC0 has [no approval from the OSI](https://opensource.org/faq#cc-zero), so to avoid issues with purists, 2-clause BSD or MIT would probably work best.
