### ISSUE TITLE
www.monocypher.org is parked

### ISSUE THREAD

**Issue by mikejsavage** [LoupVaillant/Monocypher#86]
www.monocypher.org

Adding an issue for this so it doesn't get forgotten

**Comment by LoupVaillant** [comment]
Ah, yes, thanks. I'll do it.

**Comment by CuleX** [comment]
This might also affect the SEO, possibly at least partially explaining the results @secworks saw in #84.

**Comment by secworks** [comment]
;-) Mos def.

**Comment by LoupVaillant** [comment]
OK, done. I'll close this when the redirection is verified (with the 3 hours TTL, things are going slow).
