### ISSUE TITLE
Build target self is broken on OpenBSD 6.1

### ISSUE THREAD

**Issue by CuleX** [LoupVaillant/Monocypher#9]
OpenBSD 6.1 is the current version of OpenBSD. It ships gcc 4.2.1. While OpenBSD is going to use clang for 6.2, [this only affects i386 and amd64 targets for now](https://marc.info/?l=openbsd-cvs&m=150109829003860).

In `tests/self.c`, there are constructions that attempt to build a const value by involving another const value. gcc on OpenBSD 6.1 rejects those, saying "error: initializer element is not constant". Affected lines in `tests/self.c` are 295, 296, 334, 376, 377, 416, 417, 453.

This currently breaks the build. I would normally file a pull request, but in this case, I'm not sure how you would want it to be handled, I could imagine simply hardcoding the values, hardcoding the values and extending the comments (usually pushing them past the 80 column boundary), or using macros.

(After fixing this, the build on OpenBSD 6.1 goes through without issues. There's a warning that the `ALIGN` macro is redefined in `tests/ed25519-donna/ed25519-donna-portable.h`, conflicting with the one in `/usr/include/sys/param.h`, but the code in the donna implementation is out of your control.)

**Comment by LoupVaillant** [comment]
I think macros would be best, that would make the test easier to modify.

I also think we should add a global INPUT_MULTIPLIER and a C_MAX_SIZE_MULTIPLIER and remove the corresponding magic numbers (4 and 2 respectively). That way we can tweak their size globally for more stringent tests. But that probably belongs to a separate commit.
