### ISSUE TITLE
Date in ChangeLog, and possible news page?

### ISSUE THREAD

**Issue by secworks** [LoupVaillant/Monocypher#90]
(This is really for the monocypher home page, but github issues are nice.)

I would like to suggest to add date information to items on the ChangeLog page. There is information that there are a 2.0.0 version, but no info when it was released. Since there is neither a News-page, a potential user won't be able to figure out how old a release is. Is the project really active or is it in fact stale and unsupported? It is hard to know without date information for releases. How about at least add a News-section or release info section at the top of the home page? Makes it easier to promoto Monocypher too. 

The Github repo of course shows a lot of info about activity. And since the first three search items on Google for "Monocypher" or "monocypher" is to Github, this is where people will end up. But still I think the home page would be improved with date info. (The actual home page does not appear on the first page of search results anymore.)

**Comment by LoupVaillant** [comment]
Oh yes, dates are indeed missing. I'll dig up the dates of the relevant tags, and the dates in the changelog.

I don't have a news page, but I do have an RSS/Atom feed. Still, you're right, I'll think about the news page.

> And since the first three search items on Google for "Monocypher" or "monocypher" is to Github, this is where people will end up

I'll put a proper 301 redirection from my website, hopefully this will help with SEO.

Still, if you'll allow me a small rant, _"people"_ need to remember how to type URLs. I've even seen computer professionals type "monocypher.org" in the freaking search box. Maddening. Besides, https://monocypher.org is the first result on DuckDuckgo, Bing, and Yahoo. Too bad they don't even matter.

---

> Is the project really active or is it in fact stale and unsupported?

Or done? There is a chance Monocypher has already reached that state. I'm confident it's at least very close. Once done, there won't be more releases, because it won't need any. It's a pity we can't readily distinguish between stale and done. (Still, there will be activity *around* Monocypher: language bindings, tools, examples… Definitely news worthy.)

Activity by the way is one thing that actually worries me about Libsodium. It has once been audited by a security company. This is good. But then it _changed_. How trustworthy are those changes?

**Comment by secworks** [comment]
Good point about projekt maturity and the difficulty to distinguish between a mature and a stale project. I have added a status section to my cores where I state if I considered it to be mature, how well it has been tested etc. Not sure if anybody would read anyway. I used to have that info at the bottom of the README and ended up getting lots of questions.

**Comment by secworks** [comment]
And forget about getting people to type URLs. That train left the station years ago.

People want to use words and sentences. Good search engines allow them to do that and have become so good that it is the way people expects things to work on the web and will not change back.

**Comment by LoupVaillant** [comment]
The redirection is now done. Hopefully Google will see that.

While we're considering a News section, I realise the main page could be reworked entirely. I was already thinking about moving the benchmark to a separate more detailed page (when [this](https://www.reddit.com/r/crypto/comments/7yf6t0/how_can_we_select_algorithms_in_libsodium/) is resolved), but we could go further.

I'm thinking of replacing the Documentation, Download, Test suite, and perhaps Customisation sections by a single "Getting started" section.

**Comment by CuleX** [comment]
I don't have hard feelings about the website, but I would like to keep a direct link to the manual on there. I'm sure the Windows users with no tooling for man pages will appreciate it.

**Comment by LoupVaillant** [comment]
> I would like to keep a direct link to the manual on there.

You mean on the landing page, in addition to the navigation bar on top? If so, I can still put it inside the "getting started" section.

The direct link from the README.md will definitely stay. As will the generated html pages inside the tarball, in case the poor Windows user cannot access the internet for some reason.

**Comment by secworks** [comment]
I think the idea of moving benchmarks to a separate page is a good idea. Also Test suite, customization on a "Getting started" sounds good. But I would suggest having "Documentation" (also) as separate heading at the top.

**Comment by secworks** [comment]
@CuleX Having the HTML version of the man pages directly in the source would solve that tooling issue for Windows users and other users too. ;-)

**Comment by LoupVaillant** [comment]
> I would suggest having "Documentation" (also) as separate heading at the top.

There already is "manual", which point to the [introduction man page](https://monocypher.org/manual/), which itself points to the other pages. Isn't that enough? (There of course will be another link in the "getting started" section itself.)

> Having the HTML version of the man pages directly in the source would solve that tooling issue

They're already in the tarball, and the tarball generation procedure is encoded in a make rule. That tarball is even distributed on GitHub on the [releases page](https://github.com/LoupVaillant/Monocypher/releases), should someone (or some search engine) be allergic to the official web site. I understand this could have been a problem before 1.0.1 (the first tarball with properly generated HTML pages), but I think we're good now.

**Comment by LoupVaillant** [comment]
We now have a news section at the bottom of the [landing page](https://monocypher.org/). I think we can close this.

**Comment by secworks** [comment]
I would possibly suggest go move news up to before the "Getting started" section. At least keep one entry there (not the whole release log).

Otherwise it looks really good. Have a nice weekend.

**Comment by LoupVaillant** [comment]
[There](https://monocypher.org/), the news are above the fold now. Had to do some trickery to make it less invasive.

**Comment by secworks** [comment]
Looks really good.
