### ISSUE TITLE
Integrate tests from google

### ISSUE THREAD

**Issue by rain-1** [LoupVaillant/Monocypher#99]
https://github.com/google/wycheproof/blob/master/testvectors/eddsa_test.json#L94

thanks to thaidn_ for sharing this

**Comment by LoupVaillant** [comment]
First time I see something useful from wycherproof (last time I checked, it didn't test EdDSA, or any algorithm used by Monocypher). I'll integrate it as soon as possible.

**Comment by rain-1** [comment]
Why is this closed

**Comment by LoupVaillant** [comment]
Because it is done, see the commit that closed the issue.
